name: dotnet package

on: 
  push:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.12.0
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.12.0
        with:
          useConfigFile: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install OpenSSL
        run: sudo apt-get install libssl3 -y
          
      - name: Restore Nuget packages
        run: dotnet restore HelloWorld.csproj

      - name: Test
        run: dotnet test HelloWorld.csproj        

      - name: Build project
        run: dotnet build HelloWorld.csproj -c Release -o build

      - name: Pack
        run: dotnet pack HelloWorld.csproj -c Release --output nupkgs /p:Version=${{ env.GitVersion_NuGetVersion }}

      - name: Create IIS Deployment Package
        run: |
          dotnet publish HelloWorld.csproj -c Release -o publish \
            --runtime win-x64 \
            --self-contained false \
            /p:Version=${{ env.GitVersion_NuGetVersion }}
          cd publish
          zip -r ../webapp.zip *

      - name: Upload IIS Deployment Package
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: webapp.zip
          retention-days: 5