name: dotnet package

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Install OpenSSL
        run: sudo apt-get install libssl3 libssl1.1 -y
          
      - name: Restore Nuget packages
        run: dotnet restore HelloWorld.csproj

      - name: Build project
        run: dotnet build HelloWorld.csproj -c Release -o build  