name: dotnet package

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 3.1.x

      - name: Install OpenSSL 1.1
        run: |
          wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
          
      - name: Restore Nuget packages
        run: dotnet restore HelloWorld.csproj

      - name: Build project
        run: dotnet build HelloWorld.csproj -c Release -o build  